import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

# Input CSV generated by authorsFileTouches
INPUT_CSV = 'data/authorsFileTouches.csv'

# Read in CSV
df = pd.read_csv(INPUT_CSV)

#convert file names to numbers for ease of reading
df['file_num'] = df['file'].astype('category').cat.codes + 1

#Convert date strings to datetime
df['date'] = pd.to_datetime(df['date'])

# Calc weeks since first commit
df['week'] = (( df['date'] - df['date'].min() ).dt.days / 7).astype(int)

#assign colors to authors
authors = df['author'].unique()
colors = plt.cm.tab20(range(len(authors))) #20 authors max 
color_map = dict(zip(authors, colors))

# Map author to color for each row
df['color'] = df['author'].map(color_map)

#Create scatter plot
plt.figure(figsize=(12, 8))

for author in authors:
    author_df = df[df['author'] == author]
    plt.scatter(author_df['file_num'], author_df['week'], c=[color_map[author]], label=author, alpha=0.6)

plt.xlabel('File')
plt.ylabel('Weeks')
plt.title('File Touches Over Time By Author')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45)
plt.tight_layout()

# Save plot to file
plt.savefig('scatterplot_file_touches.png')
plt.show()
